#!/usr/bin/env ruby

def merge_javascript
  # =============
  # This script performs predeploy tasks such as packaging up and minimizing javascript/css
  # =============

  puts "========================="
  puts "RUNNING PREDEPLOY TASKS"
  puts "========================="

  # Clean Up Javascript Min
  puts "Clearing out javascripts/min"
  puts `mkdir -p ./public/javascripts/min`
  puts `rm -f ./public/javascripts/min/*.js`
  puts "========================="

  package_js("COMMON", "common")
  package_js("COMPONENTS", "components")
  package_js("JQUERY.ext", "jquery.ext")
  package_js("LIBRARIES", "libraries")

  # Clean Up Javascript Min
  # puts "Cleaning up javascripts/min"
  # puts `rm -f ./public/javascripts/min/*.concat.js`
  # puts "=========================\n\n"

  # Rebuild Sass
  puts "Rebuilding SASS"
  puts `rake sass:rebuild`
  puts "========================="

  puts "Clearing out stylesheets/min"
  puts `mkdir -p ./public/stylesheets/min`
  puts `rm -f ./public/stylesheets/min/*.css`
  puts "========================="

  puts "Packaging up application.css"
  puts `cp ./public/stylesheets/application.css ./public/stylesheets/min/application.concat.css`
  puts `java -jar ./script/jar/yuicompressor-2.2.4.jar ./public/stylesheets/min/application.concat.css > ./public/stylesheets/min/application.css`
  puts "finished..."
  puts "========================="
  
  package_css("COMMON", "common")
  package_css("COMPONENTS", "components")

  # Clean Up CSS Min
  # puts "Cleaning up stylesheets/min"
  # puts `rm -f ./public/stylesheets/min/*.concat.css`
  # puts "========================="
end

def package_js(name, path)
  # Package up the javascript files
  # It relies on having Java installed
  # --nomunge               Minify only, do not obfuscate
  # --preserve-semi         Preserve all semicolons
  # --preserve-strings      Do not merge concatenated string literals
  puts "Packaging up #{name}"
  puts `cat ./public/javascripts/#{path}/*.js > ./public/javascripts/min/#{path}.concat.js`
  puts `java -jar ./script/jar/yuicompressor-2.2.4.jar --nomunge --preserve-semi --preserve-strings ./public/javascripts/min/#{path}.concat.js > ./public/javascripts/min/#{path}.js`
  #puts `mv ./public/javascripts/min/#{path}.concat.js ./public/javascripts/min/#{path}.js` #TEMP
  puts "finished..."
  puts "========================="
end

def package_css(name, path)
  puts "Packaging up #{name} Stylesheets to min/#{path}.css"
  puts `cat ./public/stylesheets/#{path}/*.css > ./public/stylesheets/min/#{path}.concat.css`
  puts `java -jar ./script/jar/yuicompressor-2.2.4.jar ./public/stylesheets/min/#{path}.concat.css > ./public/stylesheets/min/#{path}.css`
  puts "finished..."
  puts "========================="
end

merge_javascript